/// <reference types="vitest/config" />
import { fileURLToPath } from "node:url";
import { defineConfig, loadEnv } from "vite";

// The repo root holds the per-worktree .env.local (generated by scripts/wt-env.sh).
const envDir = fileURLToPath(new URL("..", import.meta.url));

export default defineConfig(({ mode, command }) => {
  const env = loadEnv(mode, envDir, "");
  const apiPort = env.API_PORT ?? "8000";
  const webPort = Number(env.WEB_PORT ?? "5173");

  // D2 (spec 013): un build de producción no puede contener el despachador
  // de mocks bajo ninguna circunstancia (D1 ya lo bloquea en runtime, pero
  // esto corta el build mismo si alguien lo intenta, en vez de dejarlo pasar
  // con solo un warning que se pierde en el log). Se chequea `process.env`
  // además de `env` porque así es como llega `VITE_USE_MOCKS=true pnpm build`.
  if (command === "build") {
    const useMocks = (env.VITE_USE_MOCKS ?? process.env.VITE_USE_MOCKS ?? "").trim().toLowerCase();
    if (useMocks === "true") {
      throw new Error(
        "VITE_USE_MOCKS=true en un build de producción: los datos de prueba nunca pueden " +
          "terminar en el bundle real (spec 013). Sacá la variable y volvé a compilar.",
      );
    }
  }

  return {
    envDir,
    server: {
      port: webPort,
      strictPort: true,
      proxy: {
        // Same-origin API in dev: /api/health -> http://localhost:<API_PORT>/health
        "/api": {
          target: `http://localhost:${apiPort}`,
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
        },
      },
    },
    test: {
      environment: "node",
      include: ["src/**/*.test.ts"],
    },
  };
});
