/// <reference types="vitest/config" />
import { fileURLToPath } from "node:url";
import { defineConfig, loadEnv } from "vite";

// The repo root holds the per-worktree .env.local (generated by scripts/wt-env.sh).
const envDir = fileURLToPath(new URL("..", import.meta.url));

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, envDir, "");
  const apiPort = env.API_PORT ?? "8000";
  const webPort = Number(env.WEB_PORT ?? "5173");

  return {
    envDir,
    server: {
      port: webPort,
      strictPort: true,
      proxy: {
        // Same-origin API in dev: /api/health -> http://localhost:<API_PORT>/health
        "/api": {
          target: `http://localhost:${apiPort}`,
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
        },
      },
    },
    test: {
      environment: "node",
      include: ["src/**/*.test.ts"],
    },
  };
});
